version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 0
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 0
